server:
  port: 8090

spring:
  security:
    user:
      name: disabled
      password: disabled
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  cloud:
    gateway:
      mvc:
        routes:
          - id: User-Service
            uri: http://localhost:8089
            predicates:
              - Path=/user/**
              - Method=GET,POST,PUT,DELETE,PATCH
            filters:
              - StripPrefix=1


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.truecodes.gateway.JwtAuthenticationFilter: DEBUG
