#spring:
#  main:
#    web-application-type: reactive
#  cloud:
#    gateway:
#      routes:
#        - id: User-Service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/user/**
#        - id: wallet-service
#          uri: http://localhost:7072
#          predicates:
#            - Path=/wallet/**
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.truecodes.gateway.JwtAuthenticationFilter: DEBUG