spring.application.name=utils
server.port=7071
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
spring.kafka.admin.fail-fast=false